name: BloodOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy BloodOps to AWS
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install OpenTofu
        run: |
          curl -fsSL https://get.opentofu.org/install-opentofu.sh | sudo bash -s -- --install-method standalone
          tofu version

      - name: Build reportlab Lambda Layer
        run: |
          mkdir -p terraform/layer/python
          pip install reportlab -t terraform/layer/python/
          cd terraform/layer
          zip -r ../reportlab_layer.zip python/
          cd ../..

      - name: Create zips directory
        run: mkdir -p terraform/zips

      - name: Tofu Init
        working-directory: terraform
        run: tofu init

      - name: Tofu Plan
        working-directory: terraform
        run: tofu plan

      - name: Tofu Apply
        working-directory: terraform
        run: tofu apply -auto-approve

      - name: Deploy frontend to S3
        run: |
          aws s3 sync frontend/ s3://bloodops-frontend-bucket/ \
            --exclude "admin.html" \
            --delete